services:
  frontend:
    image: registry.spokayhub.top/frontend_crisisview-main:${IMAGE_TAG:-latest}
    container_name: frontend_crisisview-main-stg
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - ./frontend_crisisview-main-stg.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
