sonar.projectKey=frontend_crisisview-main
sonar.projectName=frontend_crisisview-main
sonar.projectVersion=1.0

sonar.sources=app

sonar.exclusions=node_modules/**,build/**,public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
